name: Create and publish a Docker image
on: push
jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Shallow Clone (depth=1)
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup GitHub context
        id: context
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build docker image
        run: docker build -t $IMG_NAME -f ./Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.IMG_NAME }}:latest
            ${{ env.IMG_NAME }}:${{ steps.context.outputs.sha8 }}