name: docker-release
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    uses: josephrodriguez/github-workflow/.github/workflows/docker-build-release-by-digest.yaml@main
    with:
      github_repository: ${{ github.repository }}
      docker_digest_name: digests
      docker_push_enabled: true
      docker_file_name: "./Dockerfile.jvm"
      docker_image_name: ${{ github.repository }}
      docker_platform: ${{ matrix.platform }}
      docker_registry_url: docker.io
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  push:
    uses: josephrodriguez/github-workflow/.github/workflows/docker-push-release-by-digest.yaml@main  
    needs:
      - docker
    with:
      docker_registry_url: docker.io
      docker_image_name: ${{ github.repository }}
      docker_image_tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
      docker_digest_pattern: digests-*
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_PASSWORD }}