name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            os_version: "ubuntu-latest"
          - platform: "linux/arm64"
            os_version: "ubuntu-latest"
    uses: josephrodriguez/github-workflow/.github/workflows/java-docker-relase.yaml@main
    with:
      os_version: "ubuntu-latest"
      github_repository: ${{ github.repository }}
      docker_platform: ${{ matrix.platform }}
    secrets:
      DOCKER_REGISTRY_URL: ghcr.io
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}