name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: josephrodriguez/github-workflow/.github/workflows/java-docker-relase.yaml@main
    with:
      os_version: "ubuntu-latest"
      github_repository: ${{ github.repository }}
      docker_platform: ${{ matrix.target }}
    secrets:
      DOCKER_REGISTRY_URL: ghcr.io
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}