name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  DeployToPlatforms:
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    uses: josephrodriguez/github-workflow/.github/workflows/java-docker-relase.yaml@main
    with:
      github_repository: ${{ github.repository }}
      docker_context: "."
      # docker_platform: ${{ matrix.platform }}
      docker_push_enabled: false
      docker_file_name: "./Dockerfile"
      os_version: "ubuntu-latest"
    secrets:
      DOCKER_REGISTRY_URL: ghcr.io
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}