name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    uses: josephrodriguez/github-workflow/.github/workflows/java-docker-relase.yaml@main
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64 
    with:
      os_version: "ubuntu-latest"
      github_repository: ${{ github.repository }}
      docker_platform: ${{ matrix.platform }}
    secrets:
      DOCKER_REGISTRY_URL: ghcr.io
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}