name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  docker:
    strategy:
      fail-fast: true
      matrix:
        version:
          - jvm
          - native        
        platform:
          - linux/amd64
          - linux/arm64
    uses: josephrodriguez/github-workflow/.github/workflows/docker-build-release-by-digest.yaml@main
    with:
      github_repository: ${{ github.repository }}
      docker_digest_name: digests-${{ matrix.version }}
      docker_push_enabled: true
      docker_file_name: "./Dockerfile.${{ matrix.version }}"
      docker_image_name: ghcr.io/${{ github.repository }}
      docker_platform: ${{ matrix.platform }}
      docker_registry_url: ghcr.io
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push:
    strategy:
      fail-fast: true
      matrix:
        version:
          - jvm
          - native
    uses: josephrodriguez/github-workflow/.github/workflows/docker-push-release-by-digest.yaml@main  
    permissions:
      packages: write
      contents: read
    needs:
      - docker
    with:
      docker_registry_url: ghcr.io
      docker_image_name: ghcr.io/${{ github.repository }}
      docker_image_tags: type=raw,value=${{ matrix.version }}-{{date 'YYYYMMDDhhmm'}}-{{sha}}
      docker_digest_pattern: digests-${{ matrix.version }}-*
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}        