name: ghcr-release
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  DeployToPlatforms:
    uses: josephrodriguez/github-workflow/.github/workflows/java-docker-relase.yaml@main
    with:
      os_version: "ubuntu-latest"
      github_repository: ${{ github.repository }}
      docker_context: "."
      docker_push_enabled: false
      docker_file_name: "./Dockerfile"
    secrets:
      DOCKER_REGISTRY_URL: ghcr.io
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}