name: gradle-build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build
      run: ./gradlew clean build --scan --warning-mode all

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./target/jacoco-report
        flags: unittests
        name: codecov-umbrella
        verbose: true


    - name: Generate Summary
      run: |
        # Extract the Build Scan URL from the logs
        scan_url=$(grep -o 'https://gradle.com/s/[^ ]*' <<< "$GITHUB_RUN_LOG" | tail -1)

        # Check if the scan URL was found
        if [ -z "$scan_url" ]; then
          echo "No Gradle Build Scan URL found."
          exit 1
        fi

        # Write the URL to the GitHub Actions summary
        echo "## Gradle Build Scan" >> $GITHUB_STEP_SUMMARY
        echo "The [Gradle Build Scan]($scan_url) is available for this build." >> $GITHUB_STEP_SUMMARY        

  dependabot:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
