name: gradle-build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  gradle:
    uses: josephrodriguez/github-workflow/.github/workflows/java-gradle-build.yaml@main
    with:
      cache_gradle: true
      cache_sonar: true
      java_version: '21'
      java_distribution: 'temurin'
      gradle_enable_scan: true
      gradle_enable_sonar: true
      gradle_log_level: info
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependabot:
    needs: [gradle]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
