name: gradle-build
on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'bump/*'
  pull_request:
    branches:
      - '*'
jobs:
  gradle:
    uses: josephrodriguez/github-workflow/.github/workflows/java-gradle-build.yaml@main
    with:
      cache_gradle: true
      cache_sonar: true
      java_version: '21'
      java_distribution: 'temurin'
      gradle_enable_scan: true
      gradle_enable_sonar: true
      gradle_log_level: info
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependabot:
    needs: [gradle]
    permissions: write-all
    uses: josephrodriguez/github-workflow/.github/workflows/dependabot-merge-pull-request.yaml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
