name: maven-package

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - id: vars
      name: Setup job variables      
      run: |
        echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode clean package --file pom.xml "-Dartifact.version=${{ steps.vars.outputs.sha8 }}"
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./target/jacoco-report
        flags: unittests
        name: codecov-umbrella
        verbose: true

  dependabot:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
